### ISSUE TITLE
Невозможность запуска в linux-системах (ubuntu, dockerized alpine)

### ISSUE THREAD

**Issue by danteblank** [crinny/b0mb3r#110]
**PREREQUISITES**
OS: Ubuntu 20.04.1 (Focal)
or
DOCKER: python:3.8-alpine

**CASE**
1. git clone https://github.com/crinny/b0mb3r.git
2. cd b0mb3r
3. python3.8 ./setup.py build
4. python3.8 ./setup.py install
5. bomber or b0mb3r

**ACTUAL**
```
Traceback (most recent call last):
  File "/usr/local/bin/bomber", line 11, in <module>
    load_entry_point('b0mb3r==3.1.4.1', 'console_scripts', 'bomber')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2854, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2445, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2451, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/usr/local/lib/python3.8/dist-packages/b0mb3r-3.1.4.1-py3.8.egg/b0mb3r/cli.py", line 10, in <module>
NotADirectoryError: [Errno 20] Not a directory: '/usr/local/lib/python3.8/dist-packages/b0mb3r-3.1.4.1-py3.8.egg/b0mb3r'
```

**EXPECTED**
Приложение запускается

**Comment by crinny** [comment]
1. Работает ли с Python 3.7?
2. Работает ли при установке через pip: `pip install b0mb3r --force-reinstall`?

**Comment by danteblank** [comment]
Пытался установить в чистый Alpine-docker образ, с 3.7, так там он отваливается сразу при исполнении setup.py
На основной Ubuntu системе стоит 3.8, ошибка как и выше.
--force-reinstall добавлял в Dockerfile, не помогло.

**Comment by danteblank** [comment]
Решил проблему выбором другого базового образа.

Вдруг кому надо будет, то вот:

FROM python:3.7-slim-buster

WORKDIR /b0mb3r

# copy the content of the local src directory to the working directory
COPY ./ .

RUN pip install b0mb3r --force-reinstall

# install dependencies
RUN python ./setup.py build
RUN python ./setup.py install

CMD ["b0mb3r"]
