### ISSUE TITLE
не робит

### ISSUE THREAD

**Issue by wolf228z** [crinny/b0mb3r#14]
при python main.py:
Traceback (most recent call last):
  File "main.py", line 20, in <module>
    module = __import__(service[:-3])
  File "services/sunlight.py", line 1, in <module>
    from service import Service
  File "services/service.py", line 32
    print(f'{datetime.now().strftime("%Y-%m-%d %H:%M:%S")} - {name}: {message}')
                                                                              ^
SyntaxError: invalid syntax
при python3 main.py:
Traceback (most recent call last):
  File "main.py", line 10, in <module>
    from flask import Flask, request, render_template, abort
  File "/usr/local/lib/python3.7/dist-packages/flask/__init__.py", line 19, in <module>
    from . import json
  File "/usr/local/lib/python3.7/dist-packages/flask/json/__init__.py", line 31, in <module>
    _slash_escape = "\\/" not in _json.dumps("/")
AttributeError: module 'simplejson' has no attribute 'dumps'

**Comment by Slivondiy** [comment]
В води сначала: "pkg install python" потом устанавливай.
Потом в води: "pkg install git" тоже устанавливай
После установки этих двух прог) пиши вот это:

**Comment by wolf228z** [comment]
все сделал по инструкции, ничего не изменилось

**Comment by wolf228z** [comment]
у меня установлен linux, это никак не влияет?

**Comment by Slivondiy** [comment]
> у меня установлен linux, это никак не влияет?

через телефон?

**Comment by wolf228z** [comment]
на ноутбуке

**Comment by crinny** [comment]
Введи в командную строку `pip uninstall simplejson`

**Comment by UzHACK3R** [comment]
У  меня ошибка на Termux 
Вот посмотрите 


Listening on http://192.168.1.102:8080/
 * Serving Flask app "main" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
Traceback (most recent call last):
  File "main.py", line 86, in <module>
    app.run(host='0.0.0.0', port=8080, threaded=True)
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/flask/app.py", line 990, in run
    run_simple(host, port, self, **options)
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/werkzeug/serving.py", line 1009, in run_simple
    inner()
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/werkzeug/serving.py", line 962, in inner
    fd=fd,
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/werkzeug/serving.py", line 805, in make_server
    host, port, app, request_handler, passthrough_errors, ssl_context, fd=fd
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/werkzeug/serving.py", line 698, in __init__
    HTTPServer.__init__(self, server_address, handler)
  File "/data/data/com.termux/files/usr/lib/python3.7/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/data/data/com.termux/files/usr/lib/python3.7/http/server.py", line 137, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/data/data/com.termux/files/usr/lib/python3.7/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use

**Comment by crinny** [comment]
@UzHACK3R перезапусти Termux, закрой его через шторку уведломений. Не помогает - перезагрузи телефон.

**Comment by crinny** [comment]
Закрыл из-за отсутствия активности. Если проблема не была исправлена, переоткройте Issue.

**Comment by sergeyfilippov1** [comment]
@Slivondiy аххаха, долбан блять, ошибку видишь?

**Comment by 0susboy0** [comment]
@sergeyfilippov1 слыш ты, чорт

**Comment by newpotsdev** [comment]
@UzHACK3R процесс бомбера уже запущен, проверьте другие окна в термуксе если они есть.
